name: "🚀 Create Release"
on:
  workflow_call:
    inputs:
      TARGET_REPOSITORY:
        required: false
        type: string
        default: ${{ github.repository }}
        description: "The name of the repository where the release should be created. If not specified, uses the current repository."
      TARGET_BRANCH:
        description: "Target Branch to checkout"
        required: false
        type: string
        default: ${{ github.ref }}
      WORKFLOWS_ORGANIZATION:
        required: false
        type: string
        default: "ExakisNelite"
      WORKFLOWS_REPOSITORY:
        required: false
        type: string
        default: "devops-workflows"
        description: "The name of the workflows repository."
      WORKFLOWS_TARGET_BRANCH:
        description: "Target Branch to checkout"
        required: false
        type: string
        default: "main"
      ENVIRONMENT:
        required: false
        type: string
        default: production
        description: "The environment to deploy to"
      MAIN_BRANCH_TARGET_REPOSITORY:
        required: false
        type: string
        default: main
        description: "The main branch of the target repository"
      DEFAULT_BUMP:
        required: false
        type: string
        default: patch
        description: "The default bump to use when creating a new release. Can be major, minor, or patch."
      SHOULD_TAG_MAJOR:
        required: false
        type: boolean
        default: false
        description: "If set to true, the major tag will be updated to point to the major release version."
      SHOULD_TAG_LATEST:
        required: false
        type: boolean
        default: false
        description: "If set to true, the latest tag will be updated to point to the latest release."     

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Checkout Caller Repository
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.TARGET_REPOSITORY }}
          ref: ${{ inputs.TARGET_BRANCH }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: false
      - name: Bump version and push tag
        id: create_tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b
        with:
          release_branches: ${{ inputs.MAIN_BRANCH_TARGET_REPOSITORY }}
          default_bump: ${{ inputs.DEFAULT_BUMP }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: ${{ github.event_name == 'pull_request' }}
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
        if: steps.create_tag.outputs.new_version
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: ${{ github.event_name == 'pull_request' }}
      - name: Tag the major release version
        if: ${{ inputs.SHOULD_TAG_MAJOR && github.event_name == 'push' && github.ref_name == inputs.MAIN_BRANCH_TARGET_REPOSITORY }}
        uses: cloudposse/github-action-major-release-tagger@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add latest tag
        if: ${{ inputs.SHOULD_TAG_LATEST && github.event_name == 'push' && github.ref_name == inputs.MAIN_BRANCH_TARGET_REPOSITORY && github.event_name == 'push' && github.ref_name == inputs.MAIN_BRANCH_TARGET_REPOSITORY }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Action"
          git tag -fa latest -m "Update latest tag"
          git push origin :refs/tags/latest
          git push origin --tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
