name: ✉️ Notify Teams on workflow completion

on:
  workflow_call:
    inputs:
      status:
        description: "Status of the notification (success or failure)."
        type: string
        required: true
      message:
        description: "Content of the notification message."
        type: string
        required: false
      environment:
        description: "Environment for the notification."
        type: string
        required: false
        default: preprod

jobs:
  send:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - name: 🔀 Checkout code
        uses: actions/checkout@v5

      - name: 📨️ Generate message
        run: |
          # Generate notification message
          commit_message=$(git log -1 --pretty=format:"%s")
          commit_author=$(git show -s --format='%an <%ae>' "${{ github.sha }}")
          notify_date=$(date +'%d-%m-%Y %H:%M:%S')
          message="<p>Workflow <strong>${{ github.workflow }}</strong> has been completed for <strong>${{ github.repository }}</strong></p><br>"
          if [ "${{ inputs.status }}" == "success" ]; then
             message+="<p>Status: <span style='color: green;'>Success</span></p>"
          else
             message+="<p>Status: <span style='color: red;'>Failure</span></p>"
          fi
          message+="<p>Message: ${commit_message}</p>"
          message+="<p>Date: ${notify_date}</p>"
          message+="<p>Author: ${commit_author}</p>"
          message+="<p>Branch: ${{ github.ref_name }}</p>"
          message+="<p>Environment: ${{ inputs.environment }}</p>"
          message+="<p>Commit: <a href='${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}'>${{ github.sha }}</a></p>"
          message+="<p>Workflow: <a href='${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'>${{ github.run_id }}</a></p><br>"
          message+="${{ inputs.message }}"
          echo "MESSAGE=${message}" >> "$GITHUB_ENV"

      - name: ✉️ Notify Teams
        run: |
          # Send message to teams
          if ! curl --fail -X POST "${{ secrets.TEAMS_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d "{
                  \"message\": \"${MESSAGE}\"
                }"; then
            echo "❌ Failed to send notification to Teams."
            exit 1
          fi
          echo "✅ Notification sent successfully."
